---
- name: Deploy flask on gunicorn
  hosts: flaskapp01
  vars:
    user: "{{ ansible_ssh_user }}"
    proj_name: flask_app
    venv_home: "{{ ansible_env.HOME }}"
    venv_path: "{{ venv_home }}/{{ proj_name }}"
    proj_dirname: project
    proj_path: "{{ venv_path }}/{{ proj_dirname }}"
    repo_url: https://github.com/koksay/dc.git
    gunicorn_port: 8000
    locale: en_US.UTF-8
    conf_path: /etc/nginx/conf
    tls_enabled: True
    python: "{{ venv_path }}/bin/python"
    domains:
      - 192.168.1.10.xip.io
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      sudo: True
      with_items:
        - git
        - nginx
        - python-dev
        - python-pip
        - python-setuptools
        - python-virtualenv
        - supervisor
    - name: check out the flask application repository
      git: repo={{ repo_url }} dest={{ proj_path }} accept_hostkey=yes
    - name: install required python packages
      pip: name={{ item }} virtualenv={{ venv_path }}
      with_items:
        - gunicorn
        - Flask
    - name: set the gunicorn config file
      template: src=templates/gunicorn.conf.py.j2 dest={{ proj_path }}/gunicorn.conf.py
    - name: set the supervisor config file
      template: src=templates/supervisor.conf.j2 dest=/etc/supervisor/conf.d/flask.conf
      sudo: True
      notify: restart supervisord
    - name: set the nginx config file
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/flask.conf
      notify: restart nginx
      sudo: True
    - name: enable the nginx config file
      file:
        src: /etc/nginx/sites-available/flask.conf
        dest: /etc/nginx/sites-enabled/flask.conf
        state: link
      notify: restart nginx
      sudo: True
    - name: remove the default nginx config file
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx
      sudo: True
    - name: ensure config path exists
      file: path={{ conf_path }} state=directory
      sudo: True
      when: tls_enabled
    - name: create ssl certificates
      command: >
        openssl req -new -x509 -nodes -out {{ proj_name }}.crt
        -keyout {{ proj_name }}.key -subj '/CN={{ domains[0] }}' -days 3650
        chdir={{ conf_path }}
        creates={{ conf_path }}/{{ proj_name }}.crt
      sudo: True
      when: tls_enabled
      notify: restart nginx

  handlers:
    - name: restart supervisord
      service: name=supervisor state=restarted
      sudo: True
    - name: restart nginx
      service: name=nginx state=restarted
      sudo: True

